analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.8028674
  brandStrength: 0.4982079
  lightness: 1
  brandColors:
    - '#000000'
    - '#888888'
    - '#FAFAFA'
  rhythmicContrast: 0.5
typography_spectrum: 0.79882
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.9856631
favicon: null
name: Alyssa LoBello
